{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-postgres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-postgres.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.password | b64enc }}
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
  database: {{ .Values.auth.database | b64enc }}
  {{- if .Values.auth.replicationUser }}
  replication-username: {{ .Values.auth.replicationUser | b64enc }}
  replication-password: {{ .Values.auth.replicationPassword | b64enc }}
  {{- end }}
{{- end }}