apiVersion: v2
name: nginx-external
description: A Helm chart for external nginx with cloudflare tunnel integration
type: application
version: 0.1.0
appVersion: "1.27.0"
keywords:
  - nginx
  - external
  - cloudflare
  - tunnel
home: https://nginx.org/
sources:
  - https://github.com/nginx/nginx
maintainers:
  - name: Alt Team
    email: team@alt.example.com
dependencies:
  - name: cloudflare-tunnel
    version: "0.1.0"
    repository: "file://./charts/cloudflare-tunnel"