apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alt-database

resources:
  - deployment.yaml
  - secret.yaml
  - ssl-secret.yaml
  - ssl-configmap.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: postgres