apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alt-apps

resources:
  - deployment.yaml
  - secret.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/component: processing
      app.kubernetes.io/part-of: search-indexer