apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos-postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kratos-postgres.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "kratos-postgres.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos-postgres.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kratos-postgres.labels" . | nindent 4 }}
    service-type: headless
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "kratos-postgres.selectorLabels" . | nindent 4 }}
{{- end }}